feat(온보딩): 온보딩 페이지 구현
HandyBus/handybus-web-latest pull request #43
Opened 2024-11-05 04:22 UTC by gw-lim

## 개요

온보딩 페이지를 구현했습니다.

## 변경사항
### 온보딩 페이지
온보딩 페이지를 `react-hook-form`을 사용하여 퍼널 형식으로 구현했습니다.

https://github.com/user-attachments/assets/c6140e4e-babe-4651-832e-338fc86c812c

### middleware
미들웨어를 통해 `사용자가 로그인하지 않았을 때` / `로그인을 했지만 온보딩을 완료하지 않았을 때` 로그인이 필요한 페이지에 접근할 경우 `/login` 페이지로 리다이렉트 되도록 하였습니다.
현재 /mypage만 로그인이 필요한 페이지로 등록해두었습니다. 추후에 페이지가 추가될 경우 middleware의 config에서 해당 path를 추가해주면 됩니다.

https://github.com/user-attachments/assets/839bd24f-1220-4ccd-80eb-c3945baaec5a

### session
온보딩을 완료 시 session이라는 쿠키를 설정해두도록 했습니다. 이를 통해 유저의 로그인 여부를 확인할 수 있습니다.

```ts
const session = getSession();
setSession();
removeSession();
```

### 공통 이미지 업로드 api
presigned url를 통해 이미지 파일을 업로드하고 cdn url을 리턴하는 공통 api를 구현했습니다.

```ts
const imageUrl = await getImageUrl({
  key: 'users/profiles',
  file: fileData,
});
```

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. Commit message convention 참고
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-11-05 04:50 UTC, gw-lim commented on next.config.mjs
> +  },
일단 개발에 용이하도록 모든 이미지 패턴을 허용하도록 설정해두었습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/page.tsx
> +        </FormProvider>
FormProvider을 사용하여 퍼널 내의 데이터들을 저장하고 이전 단계로 돌아갔을 때에도 유지되도록 하였습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/hooks/useFunnel.tsx
퍼널에 사용되는 커스텀 훅을 구현하였습니다.
각 Step에 할당되어 있는 name을 기반으로 선택된 스탭의 화면을 Funnel에서 렌더링합니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +    useFunnel(ONBOARDING_STEPS);
퍼널 커스텀 훅을 이용하여 퍼널을 적용하였습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +      </Funnel>
온보딩에 있는 4가지 단계에 맞추어 4개의 스탭으로 분리하여 컴포넌트를 구성했습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +  };
회원가입 폼 제출을 핸들링하는 함수입니다.
이미지 파일을 url로 변환하고, 파싱한 데이터들을 유저 정보 수정 api로 보내 업데이트합니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +  };
폼 내에서 엔터키를 입력시 폼에 제출되는 현상을 방지하기 위해 넣어두었습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/steps/ProfileInfoStep.tsx
> +  };
따로 닉네임 중복 api나 버튼 ui가 없고, 다음으로 버튼을 눌렀을 때 유저 정보 업데이트 api를 통해 닉네임이 중복되어 있는지 확인하는 로직입니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/steps/PersonalInfoStep.tsx
> +  };
현재 단계에서 입력해야할 정보들이 유효한지 확인하고, 다음 단계로 넘어갑니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/components/steps/ResidenceStep.tsx
> +  }, [bigRegion, smallRegion]);
현재 화면에서 state로 관리되는 지역과 FormContext 내부에 데이터가 동기화 되도록 했습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/app/onboarding/constants/formValidation.ts
온보딩 에러 메시지 및 정규 표현식을 관리하는 상수 파일입니다.

2024-11-05 04:50 UTC, gw-lim commented on src/services/common.ts
공통 이미지 업로드 api를 구현해두었습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/utils/handleSession.ts
온보딩 완료 여부(로그인 완료 여부)를 확인할 수 있는 쿠키를 핸들링하는 함수들입니다.

2024-11-05 04:50 UTC, gw-lim commented on src/middleware.ts
config에 등록되어 있는 페이지(로그인이 필요한 페이지)에 접근할 시 session 쿠키를 확인하여 로그인 여부에 따라 redirect 시킵니다.

2024-11-05 04:50 UTC, gw-lim commented on src/components/buttons/radio-buttons/RadioButtons.tsx
RadioButtons 공통 컴포넌트가 react-hook-form의 controller으로 사용될 수 있도록 수정했습니다.

2024-11-05 04:50 UTC, gw-lim commented on src/components/Provider.tsx
리액트 쿼리 프로바이더를 추가하고, 별도의 컴포넌트로 분리해두었습니다.

2024-11-05 05:06 UTC, gw-lim commented on src/hooks/useFunnel.tsx
https://github.com/HandyBus/handybus-web-latest/pull/43

2024-11-05 05:06 UTC, gw-lim commented on src/components/buttons/radio-buttons/RadioButtons.tsx
RadioButtons 공통 컴포넌트가 react-hook-form의 controller으로 사용될 수 있도록 수정했습니다.

2024-11-05 05:06 UTC, gw-lim commented on src/components/Provider.tsx
리액트 쿼리 프로바이더를 추가하고, 별도의 컴포넌트로 분리해두었습니다.

2024-11-07 02:46 UTC, joonseong11 commented on next.config.mjs
> +  },
넵 이후에 적절한 도메인만 혀용하도록 변경해야겠네요 ㅎㅎ

2024-11-07 03:57 UTC, stonechoe requested changes
수고 많으셨습니다 👍👍👍👍

2024-11-07 03:57 UTC, stonechoe commented on src/app/auth/login/[oauth]/page.tsx
> +      if (user.ageRange === '연령대 미지정' || !user.ageRange) {
!user.ageRange인 것은 ageRange가 응답에 존재하지 않을 수 있어서 그런건가요? 타입 상 존재해야 하긴 하는데, 타입에 optional인 것을 명시하거나 (언젠가) validating을 하는 게 더 좋은 방법일 것 같아요

2024-11-07 03:58 UTC, stonechoe approved these changes

2024-11-07 05:02 UTC, gw-lim commented on src/app/auth/login/[oauth]/page.tsx
> +      if (user.ageRange === '연령대 미지정' || !user.ageRange) {
현재 데이터베이스 상에서 유저가 온보딩을 완료하지 않은 것을 ageRange가 설정되지 않은 경우로 판별하고 있습니다. 이때 ageRange가 설정되지 않았을 때의 default 값이 `연령대 미지정`이기에 해당 경우로 확인하고 있습니다. 
!user.ageRange는 타입상 존재해야하는 것은 아니고, 혹시 모를 경우를 대비하여 넣어둔 부분이라 필수적인 부분은 아닙니다. 뺴는게 좋을까요?

2024-11-07 05:27 UTC, stonechoe commented on src/app/auth/login/[oauth]/page.tsx
> +      if (user.ageRange === '연령대 미지정' || !user.ageRange) {
저는 UserType을 사용할 수 있는 다른 기능들에서도 이렇게 확인을 필수적으로 해야하나 싶어서 그랬어요.

만약 확인을 필수적으로 해야한다면, 확인을 강제하도록 타입을 `ageRange?: AgeType`으로 주고, 항상 값이 들어있는게 맞다면 최초로 값을 만들 때 제대로 확인하는게 좋을 것 같아서요!

일단은 그냥 두고 언젠가 api 응답을 validating 하는 걸 넣으면 될 것 같아요.

2024-11-07 05:36 UTC, gw-lim commented on src/app/auth/login/[oauth]/page.tsx
> +      if (user.ageRange === '연령대 미지정' || !user.ageRange) {
넵, 지금은 여기에서만 확인을 하면 되어서 따로 UserType에 옵셔널로 명시는 해두지 않았습니다. 
최초로 만들어지는 값이 서버에서 생성해주는 entity의 default 값이라 지금 상태로만 validate해도 충분하다고 생각합니다!

2024-11-07 06:02 UTC, joonseong11 commented
로컬에 내려받아서 테스트해봣는데 프로필정보에서 닉네임이 중복되엇다며 다음으로 넘어가지지 않는 버그가 발견되엇어요 ㅎㅎ

2024-11-07 06:18 UTC, joonseong11 commented on src/types/client.types.ts
고객 데이터와 관련된 타입이라는 의미인것 같아보여요

2024-11-07 08:01 UTC, joonseong11 commented on src/services/users.ts
> +export const useGetUser = () => {
get 에서 에러핸들링에 대한 대화
-> 건우님: 개발자가 일일이 화면마다 에러핸들링 처리 로직을 만드는 것 보다 나중에 공통적으로 묶어서 처리하면 더 이쁘지 않을까? useGetuser 혹은 config.ts의 instance에서 처리해버릴려고 생각하고 있었어요.

2024-11-07 08:11 UTC, gw-lim commented on src/types/client.types.ts
저희 서비스에서 공통으로 사용되는 타입들을 모아두려는 파일이었는데 말씀처럼 이름이 모호한 부분이 있는 것 같네요! common.types.ts 같은 이름은 어떠신가요?

2024-11-07 08:17 UTC, stonechoe commented on src/services/users.ts
> +export const useGetUser = () => {
확인했습니다.

2024-11-07 08:24 UTC, joonseong11 commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +    setIsSubmitting(false);
putUser가 처리중일때 setIsSubmitting이 false로 변경될 수 있어보여요 의도하신건지 궁금합니다!

2024-11-07 09:54 UTC, joonseong11 commented on src/app/onboarding/components/steps/ProfileInfoStep.tsx
> +  const showImagePreview = (file: File) => {
이미지 업로드시 파일크기 제한이랑 업로드실패시 처리로직이 필요할지도요?

2024-11-07 09:54 UTC, joonseong11 commented on src/middleware.ts
미들웨어로 쿠키처리 이쁘고 좋아요 ☺️

2024-11-07 09:56 UTC, joonseong11 reviewed
코드 곳곳에 아주 고생의 흔적이 가득 하네요~! 고생많으셨어요 코멘트 한번 확인해주세요 ㅎㅎ

2024-11-07 11:18 UTC, stonechoe commented on src/types/client.types.ts
common 괜찮네요!

2024-11-08 02:11 UTC, gw-lim commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +    setIsSubmitting(false);
현재 회원가입 요청을 보냈을 때 기다리게 되는 api 요청이 다음 두가지 입니다! 두 요청이 모두 끝나도록 기다려야 하기에 각각 다음과 같은 변수들로 로딩을 확인하도록 했습니다
1. 프로필 이미지 업로드 -> isSubmitting
2. 유저 정보 업데이트 -> isPending
usePutUser의 파라미터로 () => setIsSUbmitting(false) 같은 함수를 받을 수 있도록 해줄 수도 있었으나, 해당 함수가 닉네임 업데이트에도 쓰이기에 통일성을 위해 지금과 같은 로직을 짜게 되었습니다.
현재는 isLoading = isPending || isSubmitting 을 기반으로 로딩 여부를 확인하기에 동작상의 문제는 없습니다!

2024-11-08 02:27 UTC, gw-lim commented on src/app/onboarding/components/steps/ProfileInfoStep.tsx
> +  const showImagePreview = (file: File) => {
10MB 제한으로 해두었습니다! 업로드 실패 시 다음과 같이 토스트가 띄워지도록 했습니다.

<img width="488" alt="스크린샷 2024-11-08 오전 11 27 32" src="https://github.com/user-attachments/assets/62e0c076-1a02-48e4-963d-42cc5ee05e29">

2024-11-08 05:04 UTC, gw-lim commented on src/components/inputs/select-input/SelectInput.tsx
> -  onChange?: Dispatch<string> | Dispatch<SetStateAction<string>>;
확인해 본 결과 따로 추가하지 않더라도 타입 추론이 잘 되는 것으로 확인 됐습니다!

2024-11-08 05:17 UTC, joonseong11 approved these changes

2024-11-08 05:17 UTC, joonseong11 commented on src/app/onboarding/components/OnboardingFunnel.tsx
> +    setIsSubmitting(false);
아하 submitting이 완료되더라도 pending이 완료되지 않았을때는 정상적으로 isLoading === false로 처리되므로 문제가 없군요 굿굿

2024-11-08 05:20 UTC, merged