fix: 서버사이드에서 토큰이 정상적으로 처리되도록 수정
HandyBus/handybus-web-latest pull request #79
Opened 2024-11-29 08:37 UTC by gw-lim

## 개요
서버사이드에서 요청을 보낼 때 다음과 같은 문제가 있었습니다.

1. 요청에 쿠키가 담겨서 보내지지 않음
2. 새로 발급 받은 쿠키가 브라우저에 반영 되지 않음

이를 해결하기 위해 `Axios Interceptor`과 미들웨어에서 관련 처리를 해주도록 했습니다.

## 변경사항
### 서버사이드 쿠키 처리
첫 번째 문제를 해결하기 위해 `Axios Interceptor`에서 서버사이드 요청인 경우 쿠키를 `next/header`에서 따로 가져와서 요청에 넣어주도록 처리했습니다.
두 번째 문제는 요청에서 설정한 `set-cookie` 헤더가 브라우저에 적용되기 위해서는 클라이언트 사이드로 요청이 반환되어야 하는데, 서버사이드의 경우 그러지 않기 때문에 생긴 구조적 문제였습니다. 이로 인해 access token이 만료되어 없는 상태에서 `authInstance`를 부를 경우, `Api route`에서 새로 발급한 refresh token이 브라우저에 적용되지 않아 현재 유저가 가지고 있는 토큰이 모두 만료되어 버리는 문제가 있었습니다. 이를 해결하기 위해 미들웨어에서 인증이 필요한 path에 접근할 때 access token 여부를 확인하고 없을 시에 재발급하도록 로직을 추가했습니다. 이후 같은 페이지로 다시 redirect을 시켜 클라이언트 사이드에 토큰이 적용된 상태에서 요청을 다시 보내도록 구현했습니다.

### Progress 반영
`약관 동의를 하지 않았는지`, `약관 동의를 했는지`, `온보딩을 모두 끝냈는지`의 여부를 각각 따져 인증이 필요한 path에 접근할 때 알맞은 화면이 띄워지도록 했습니다.

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. Commit message convention 참고
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-12-03 01:26 UTC, stonechoe commented on src/constants/token.ts
> +  sameSite: 'lax',
lax로 해야하는 이유가 무엇인가요?

2024-12-03 01:30 UTC, stonechoe approved these changes

2024-12-03 01:46 UTC, gw-lim commented on src/constants/token.ts
> +  sameSite: 'lax',
쿠키 설정 값을 변경하며 돌려놓지 않은 값인 것 같습니다. 다시 strict으로 돌려둘게요

2024-12-03 02:09 UTC, stonechoe approved these changes

2024-12-03 08:04 UTC, joonseong11 requested changes
잘 봤습니다. 고생 많으셨어요. 클라이언트사이드와 서버사이드를 넘나들도록 설계된 코드들이라 한 번에 쉽게 이해되지 않아 여러번 곱씹으면서 봤어요. 

제가 이해한게 맞는지 한번 정리해볼게요. 맞는지 알려주세요. 
1) 클라이언트사이드 컴포넌트
(클라이언트) RestAPI 호출 -> AuthInstance
 : credential true로 request헤더에 담아 서버에 쿠키 전달, 클라이언트 환경에 httponly cookie 세팅
-> (서버) 미들웨어
 : 로그아웃시 토큰 제거, 온보딩<->마이페이지 리디렉션, (마이페이지에서만 요청에 엑세스 토큰이 없으면 재발급처리)
-> (서버)  api route 
: axios 요청 성공적으로 보냄, 엑세스 토큰없으면 재발급 처리,
-> (클라이언트) response
 : response cookie에 토큰 undefined 처리
 
2) 서버사이드 컴포넌트
(서버) 서버사이드 컴포넌트
-> (서버) 미들웨어
 : 로그아웃시 토큰 제거, 온보딩<->마이페이지 리디렉션, (마이페이지에서만 요청에 엑세스 토큰이 없으면 재발급처리)
-> (서버)  api route 
: axios 요청 성공적으로 보냄, 엑세스 토큰없으면 재발급 처리,
-> (서버) response
 : response cookie에 토큰 undefined 처리

서버사이드에서 다시 클라이언트사이드(브라우저)로 쿠키를 내려주지는 않지만, 마이페이지에서만 엑세스 토큰이 없으면 로그인페이지로 리디렉션 시켜버려서 브라우저에서도 쿠키를 갖고 요청을 보낼 수 있게 구현하신거군요. 
만약, 다른페이지에서도 엑세스 토큰이 없다면, 어떻게 되나요? 
미들웨어에 AuthRequiredPages에 다른 Auth 필요 페이지를 넣어둬야 의도하신대로 작동이 되겠네요?

(이런 작성하고있었는데 제멋대로 내용이 사라지고 requested changed로 작성되어버렸네요 ㅜㅜ)

2024-12-03 08:28 UTC, joonseong11 reviewed
github 의 버그인지 review 댓글이 세트로 똑같이 한뭉텅이 중복으로 생겨버려서 코멘트를 지웠는데, 다시 새로고침해보니 중복되어 있지 않고 다시 하나의 세트로만 정상적으로 나타나더라고요.. 그래서 다시 작성합니다 ㅎㅎ;;

2024-12-03 08:28 UTC, joonseong11 commented on .gitignore
> +./src/app/test/page.tsx
임시로 두시고 지우는걸 깜빡하신 걸까요?

2024-12-03 08:28 UTC, joonseong11 commented on src/app/mypage/components/Profile.tsx
> +          src={profileImage || DEFAULT_PROFILE_IMAGE}
?? 대신 || 로 변경하신 이유가 있나요?
추측해보건데 || 사용하면 빈 값이 들어오면 DEFAULT_PROFILE_IMAGE 값이 들어가게 되서 그렇게 처리하신거죠?

2024-12-03 08:28 UTC, joonseong11 commented on src/middleware.ts
> +    const response = NextResponse.redirect(new URL(req.url, req.url));
req.url이 중복으로 들어갔는데 오타일까요?

2024-12-03 09:19 UTC, gw-lim commented on src/services/config.ts
> +    req.headers.Cookie = `${REFRESH_TOKEN}=${refreshToken}; ${ACCESS_TOKEN}=${accessToken}; ${SESSION}=${session}`;
여기서 추가해주는 쿠키는 실제로 브라우저에 적용되는 쿠키가 아닌 서버사이드에서 요청을 보낼 때 브라우저가 쿠키를 동봉해주는 작업을 해주지 않아 따로 직접해주는 로직입니다! PR에 작성해둔 첫번째 문제를 해결하는 로직이라고 보시면 될 것 같아요.
따라서 실제 브라우저에 저장되는 쿠키가 아니기에 옵션들을 추가해주지 않아도 됩니다.

2024-12-03 09:22 UTC, gw-lim commented on src/app/api/[...path]/route.ts
> +  if (session?.accessToken || session?.refreshToken) {
여기서 지워주는 쿠키는 실제 accessToken과 refreshToken의 값이 아닌, session에 담긴 토큰들의 값입니다.
클라이언트 사이드에서 토큰을 업데이트 해주고 싶을 경우 session에 토큰 값들을 담아서 보내주는데요, api route에서 해당 토큰으로 accessToken과 refreshToken을 업데이트 해준 이후에, session에 담긴 값들은 더 이상 필요가 없기에 삭제해주고 있습니다.

2024-12-03 09:25 UTC, gw-lim commented on src/app/mypage/components/Profile.tsx
> +          src={profileImage || DEFAULT_PROFILE_IMAGE}
백엔드에 프로필 이미지 초기화 로직이 추가 되었는데, 이때 초기화되는 값이 빈 문자열 입니다.
기존에는 프로필 이미지가 없을 시 null 값이 왔으나 이제는 빈 문자열이 오게 되면서 이를 올바르게 처리해주기 위해 `||`으로 변경해두었어요.

2024-12-03 09:25 UTC, gw-lim commented on src/middleware.ts
> +    const response = NextResponse.redirect(new URL(req.url, req.url));
오타입니다! 수정하도록 하겠습니다.

2024-12-03 09:32 UTC, gw-lim commented
@joonseong11 
작성해주신 플로우가 대부분 맞습니다! 다만 response 부분에서 쿠키를 undefined 처리해주는 것이 아닌 세션의 쿠키를 관리한다고 생각하시면 더 맞을 것 같아요.
또한 작성해주신 것처럼 추후에 `AuthRequiredPages`에 인증이 필요한 페이지들을 추가해주어야하는 것이 맞습니다

2024-12-03 09:46 UTC, joonseong11 commented on src/services/users.ts
> +export type OnboardingProgress =
아하! ONBOARDING_COMPLETE 타입이 쓰이는 곳이 middleware.ts:33
src/app/auth/login/[oauth]/page.tsx:33 현재 이 두곳이더라고요. 그런데 client.types.ts의 ProgressType에도 ONBOARDING_COMPLETE 값이 있어서 
별로 중요해보이지는 않아보이지만 혼동될 수도 있을 거 같다는 생각을 했어요.

말씀주신대로 현재보다 더 많은 외부파일에서 사용하면 object as const 로 선언해두는게 좋아보이네요 ☺️

2024-12-03 11:46 UTC, joonseong11 commented on src/services/config.ts
> +    req.headers.Cookie = `${REFRESH_TOKEN}=${refreshToken}; ${ACCESS_TOKEN}=${accessToken}; ${SESSION}=${session}`;
혹시 여기에서 accessToken, refreshToken 값을 저장해두는건 이해했는데, 추가로 엑세스토큰과 리프레시토큰값이 담긴 session을 같이 담아두더라구요. 이건 왜 그런지 알 수 있을까요?

2024-12-03 11:53 UTC, gw-lim commented on src/services/config.ts
> +    req.headers.Cookie = `${REFRESH_TOKEN}=${refreshToken}; ${ACCESS_TOKEN}=${accessToken}; ${SESSION}=${session}`;
session의 값 또한 서버사이드에서 토큰을 업데이트해야하는지 여부를 판단할 때 사용하기에 넘겨주고 있습니다

2024-12-03 14:23 UTC, gw-lim reviewed
기존에 토큰을 업데이트하기 위해서는 session에 token 속성들을 업데이트하는 방식으로 구현하고 있었습니다. 다만 이와 같은 방식은 HTTP Only 속성의 보안성을 떨어트리고, 로직상으로도 복잡하다고 생각하여 세션과 토큰을 분리시켰습니다.
세션을 통해 토큰을 업데이트하던 로직을 삭제하고, 서버 액션을 통해 토큰을 바로 설정하는 방식으로 변경하여 더욱 직관적인 로직으로 수정했습니다.
마지막으로 한번만 더 가볍게 봐주시면 감사하겠습니다...!
@joonseong11 @stonechoe

2024-12-03 14:23 UTC, gw-lim commented on src/utils/handleCookie.ts
> +};
서버사이드에서 쿠키를 set 하는 서버 액션입니다

2024-12-03 14:23 UTC, gw-lim commented on src/utils/handleSession.ts
기존에 세션에 있던 토큰 속성을 삭제했습니다

2024-12-03 14:23 UTC, gw-lim commented on src/middleware.ts
> +};
인증이 필요한 페이지가 추가될 경우 AuthRequiredPages와 matcher에 모두 추가해주어야합니다.
config 내부에서 스프레드 연산자를 지원하지 않아 이와 같은 중복되는 방식으로 해두었습니다.

2024-12-03 14:23 UTC, gw-lim commented on src/app/api/[...path]/route.ts
>  ) => {
기존에 세션을 통해 업데이트 하던 로직을 삭제하고, 토큰이 독립적으로 업데이트 되도록 수정했습니다.

2024-12-03 14:23 UTC, gw-lim commented on src/app/auth/login/[oauth]/page.tsx
> +      ]);
세션을 통해 토큰을 업데이트하는 것이 아닌, 서버액션을 통해서 토큰 쿠키를 직접 설정하도록 변경했습니다

2024-12-04 08:08 UTC, joonseong11 approved these changes
변경사항 까지 모두 잘 봤어요 고생많으셨습니다
최신 변경사항에는 흐름이 훨씬 더 직관적으로 읽혀서 예측하면서 코드를 볼 수 있었어요 감사합니다 ☺️

2024-12-04 08:10 UTC, merged